### ISSUE TITLE
Recover from failed socket connection

### ISSUE THREAD

**Issue by anthonywebb** [anthonywebb/homebridge-cbus#14]
The other day, for some reason the socket between cgate-client.js and my cgate server failed. When that happens, the client will log errors, but we dont yet have any way to recover/recycle the connection again.  This would be a nice addition.

I am attaching some screenshots of what my logs look like when I did hit that failed socket.  Once the socket was failed anything I would try to do over that socket was failing and being logged.

![screen shot 2017-01-12 at 10 04 47 am](https://cloud.githubusercontent.com/assets/4397/21903248/5eb87258-d8bc-11e6-8c2b-a7f74b6db9d8.png)
![screen shot 2017-01-12 at 10 05 18 am](https://cloud.githubusercontent.com/assets/4397/21903247/5eb78b40-d8bc-11e6-9229-0a71bb4f2855.png)

**Comment by simonhac** [comment]
@anthonywebb i'm sure there is a better way of doing this, but in the meantime, this should work:
* upon unexpected close of any of the command, event or status sockets, throw an exception that kills the server
* use the `forever` module to keep the service available

**Comment by simonhac** [comment]
@anthonywebb i'm in this code, so i'm happy to look into this.

**Comment by simonhac** [comment]
@anthonywebb i'm enjoying using [template literals](https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Template_literals) from ES6. do you know if there is any issue with using ES6 language features and nodejs? (ie. can i expect that all nodejs runtime instances will support ES6?)

(i'm very new to this, but i can see from [node.green](http://node.green/) that template literals have worked in node.js since [v5.11.1](https://nodejs.org/en/blog/release/v5.11.1/), which was released 2016-05-05.)

**Comment by simonhac** [comment]
@anthonywebb please assign me to this (or let me know how i can assign myself).

**Comment by anthonywebb** [comment]
@simonhac it wont let me officiall assign you for some reason.  Feel free to take it on though! 👍

**Comment by simonhac** [comment]
thanks @anthonywebb -- i'm new to this, but i think [this article](https://help.github.com/articles/inviting-collaborators-to-a-personal-repository/) explains how to assign to me.

**Comment by simonhac** [comment]
fixed in v0.5.8 (PR #27)
