### ISSUE TITLE
Dimmer ramp erroneously sends two messages, one at 100%

### ISSUE THREAD

**Issue by DeanAmbrosini** [anthonywebb/homebridge-cbus#24]
When ramping a dimmer switch (with the homekit app on an iphone7) the initial command sent through is ramp to 100% then the expected.

Using SIRI to set a level works as expected.

![screenshot](https://cloud.githubusercontent.com/assets/23718510/23356433/ac2fea2a-fd29-11e6-8717-6c11ca9189a9.png)

**Comment by simonhac** [comment]
thanks @DeanAmbrosini -- i did notice this when i was in the code, but wanted to check with @anthonywebb before making what i think is the right change.

@anthonywebb homekit treats brightness as a separate attribute to on/off. as i understand it, the 'normal' behaviour for homekit dimable lights is to return to their previous dim level when toggled from 'off', rather than toggle from 100% to 0% and back again. if we are happy with a change in behaviour (to the homekit way) then the fix for this will be trivial. are you ok with that?

**Comment by simonhac** [comment]
@anthonywebb ping on the above comment.

**Comment by anthonywebb** [comment]
Honestly I dont recall why it was implemented that way.  I believe that either the homebridge side or the CBus side required it to work that way.  I almost want to say that without the 100 first, the home app did not know the device was on?  If we change this it should be tested pretty extensively to ensure it is working properly.  I'd love to get around the need for 2 calls when ramping.

**Comment by simonhac** [comment]
thanks @anthonywebb. i ran into the same problem with the fan and managed to work around it. the same strategy will work for dimmmers. will take a look at it next week.

**Comment by simonhac** [comment]
@DeanAmbrosini this should be fixed in v0.5.9. please reopen if you see it.
