### ISSUE TITLE
Adding 2nd network to config.json for CBUS/Homekit

### ISSUE THREAD

**Issue by peterconn** [anthonywebb/homebridge-cbus#62]
I would like to know whether i can just add a line to config.josn in regards to network? i have the normal network 254 but i also have a wireless network 250. When i add the address of the output i would like to control on network 250 it does not come up in homekit as its not in network 254 which is configured in home kit. Now the simple thing would be to add the group 50 which is on my wireless network to my network 254, But is there a way to add another network line to config.json? Can this be done? i have about 3-4 groups on wireless network that need to be controlled.

**Comment by MtSamsonite** [comment]
From what I read this can already be done.  I haven't tested it myself yet though do I have a use case that will require I add a device from another application group that I want to try.

From reading the homepage for the homebridge-cbus plugin it states you can include the network number and application number as parameters for an accessory.  Where you don't specify it defaults to the platform defaults.

Refer to: https://github.com/anthonywebb/homebridge-cbus and check the accessory parameters which includes:

network: (optional, defaults to client_network) C-Bus network address of the device
application: (optional, defaults to client_application) The C-Bus Application address of the device

Hope this helps.

**Comment by peterconn** [comment]
I tried that and homebridge stopped working completely. I think it was getting confused with the 254 network in the original parameters.

Regards

Peter Constantopedos
________________________________

**Comment by MtSamsonite** [comment]
@peterconn 

Peter,

I am only new at this and it is likely you have already tried everything I am about to say, so please don’t be offended if I am simply going over the basics.  I also don’t have a second Cbus network so I can’t validate if the plugin is working as it should in this respect or not,  however just in case it does assist here are a few things to check.

Are you certain the fault is not originating from an error in the config.json when you made the changes for the network number and the application number.  I have had some bad experiences with my config.json, for example edited in mac text edit and transferred to my Pi.  When I view the file it looks perfect but homebridge fails to load it.  This was due to some form of character encoding used on Mac text edit that my Pi did not seem to like.  If I create/edit files using nano on the Pi I had no problems.

Similarly did you validate the config.json file using a validation tool.  I have had errors that were hard to spot, but using an online validation tool assisted.

When you specified the network number and application group in the accessory configuration in config.json did you put these values in quotes.  I know in the platform settings where the network is specified it uses a number, however in the sample config.json file it shows when specifying an accessory it uses a string for the network number (it is enclosed in quotes).   I would try both in quotes and without for network and application in the accessory section to see what happens.

When you start homebrdige and it bombs out does it say why?  Usually it will have an error of some sort.  I know if the fault is with the config.json file it pretty much states that in the errors you see when it tries to load.

Mike

**Comment by peterconn** [comment]
Thanks Mike, I had no errors with my config.json and I always check with validation tool prior to adding. Like I said I have it working and I don't get any errors. Thanks for your help anyway.
