### ISSUE TITLE
Scenes

### ISSUE THREAD

**Issue by peteroz12** [anthonywebb/homebridge-cbus#65]
Is it possible to have cbus scenes show up? maybe as a switch?

**Comment by PhilPearson** [comment]
I'm not sure what use this would be.
1. Homekit itself supports the ability to create custom scenes.
2. CBus scenes can be actuated through the use of 'scene triggers'.

**Comment by DarylMc** [comment]
@PhilPearson 
Have you tried to use Homebridge to turn on a CBus scene trigger?

This is what CGate log shows when Homebridge sends command
**761 cmd3 - Command: [160] on //OFFICE/254/202/1
766 cmd3 - Response: [145] 402 Operation not supported by: //OFFICE/254/202/1 (Parameter level not found)**

This is CGate log from activating scene trigger at a key input.
**#s# # trigger min //OFFICE/254/202/1  #sourceunit=4 OID=8f6fda30-a043-1035-a041-a4e6aef93f8d
#s# # trigger max //OFFICE/254/202/1  #sourceunit=4 OID=8f6fda30-a043-1035-a041-a4e6aef93f8d**

**Comment by PhilPearson** [comment]
Yeah, I get the same thing.
Seems cgate doesnt like you sending RAMP commands to the trigger application.
Needs to be in the format of
TRIGGER EVENT //OFFICE/254/202/1 n
Where n = action selector

**Comment by RickHOZ** [comment]
Hi All, I am also trying to run some scenes that are currently set up on my Cbus Colour C-touch.

The reason is I have quite a cool effect (At least I think so) running in our display case in the lounge room.

See short video: https://www.dropbox.com/s/wb7ugvvgu9urd9f/IMG_6832.mov?dl=0

It does look better when it is darker Haha.

So it is really a very simple animation you can see, one set of lights ramps from 5% to 95% while the other set is ramping down from 95% to 5% and it's on a loop.

Would love some suggestions of how to activate from either Homkit through Cbus or Homekit through my ELKm1.

Thanks, everybody.

p.s. Phil, I'm seeing exactly the same thing when I tried it.

**Comment by PhilPearson** [comment]
@RickHOZ, unless you can trigger your scenes using the lighting application, you'll need to wait until someone has created a new 'scenes' accessory which, looking through the code, will require modification to at least the cgate client library.

**Comment by RickHOZ** [comment]
Hi Phil, Thanks. When you say through the lighting application are you meaning using the ELKM1 ?

Sorry, not sure what you mean. I know I am pushing it a bit, I can currently turn it on using the Ctouch panel, Just be nice to be able to use Home. Thanks

Rick

**Comment by PhilPearson** [comment]
In PICED (what you use to program the CTouch), you can change the 'Scene Trigger' Application to 'Lighting'.
You'll get warnings about how this is not a good idea but if your careful and understand what they are warning about its all good.
Not sure if this is something you can do without PICED though.

**Comment by RickHOZ** [comment]
Ok, I'll go into PICED and see what I can do worth giving it a try.

**Comment by PhilPearson** [comment]
Well that wasn't as hard as I was expecting it to be.
I've got scene triggers working here. Just need to tidy up the code and I'll submit an update.

**Comment by RickHOZ** [comment]
Hi Phil, wow, fantastic. I have been trying all sorts of things including the logic engine on the Colour Ctouch but it was certainly not a very nice work around. Look forward to getting my hands on the update. Have a great night.
